spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    student:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost/student
      username: root
      password: root
    test001:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost/test001
      username: root
      password: root
  aop:
    auto: true
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener: # 开启ACK
      direct:
        acknowledge-mode: manual #手动确认
      simple:
        acknowledge-mode: manual #手动确认
server:
  port: 80
#扫描mapper.xml
#mybatis:
#  mapperLocations: classpath*:/Mapper/*.xml
#  typeAliasesPackage: com.xmj.springbootdemo.entity
#  configuration:
#    callSettersOnNulls: false
# 打印sql
logging:
  level:
    com.xmj.springbootdemo.mapper: debug

